sdk-setup/src/mer-sdk-chroot

*Attention:* Temporarily on top of branch 'jb36783', the destination will be changed to 'master' once jb36783 is merged.
This is not only mutually exclusive with --login; its effect also
differs from what the original author apparently thought to be.

mer-sdk-chroot: Do not pass --preserve-environment to 'su'

---

sdk-setup/src/sdk-manage

This has been broken since commit
8c798b0bd888943cfdf6622e41eafc8b8a7d491f ([sdk-manage] Eliminate
--use-chroot-as option) - 'sudo -i' has the effect of 'cd'.
(adapted from commit 965e901de680b2820e7d91959a37622bd59d4601)

[sdk-manage] Fix usage outside of home directory. Contribute to JB#39655

---

sdk-setup/src/sdk-setup-enginelan

Using the SDK on a machine without internet connection available, the
original configuration led to default gateway being set for this
interface, which is the interface connected to the virtual network for
communication between build engine and emulator. I haven't found a
better way to fix this. Tried reordering the services, using
AlwaysConnectedTechnologies and EnableOnlineCheck config options and
more, with no effect.

Prevent ConnMan setting an invalid gateway

---

sdk-setup/src/mer-sdk-chroot

The main motivation for this is the issue with varying status of
moving from /dev/shm to /run/shm among distributions.
Signed-off-by: Martin Kampas <martin.kampas@jolla.com>

[mer-sdk-chroot] Make bind mounts more robust. Contributes to JB#27928

---

sdk-setup/src/mb2

Adds option -n or --no-deps
Sometimes it is useful to do the mb2 operations on a target without
updating package dependencies (for example, having installed
locally built version of dependency for testing). Add option to
disable the dependency updating so that target stays in proper state
for the duration of build etc.
For example to build without updating dependencies
mb2 -t target -n build
[mb2] Add option to not update target dependencies. Fixes JB#42728

mb2: Add option to not update target dependencies.

---

sdk-setup/src/mb2

The most likely error in this case is the presence of unmerged changes.

[mb2] Handle errors in saving working directory state. Contribute to JB#42967

---

sdk-setup/etc/sshd_config_engine

Build engine only has C, POSIX and en_US.utf8 locales defined. Forwarding
environment variables containing any other locales results in errors.

[sshd] Don't accept locale environment variables. Contribute to JB#43225

---

sdk-setup/src/rpmvalidation

Busybox's find does not recognize '-printf'.
Also eliminated the suppression of find's stderr - hidding the error
message made debugging this harder.

[rpmvalidation] Fix busybox compatibility under sb2. Fixes JB#44979

---

rpm/sdk-setup.spec

/home is shared between sdk engine and targets

[zypp] Redirect the new zypp cache location in /home back to /var/cache. Fixes JB#45318

---

sdk-setup/src/mer-sdk-chroot
sdk-setup/systemd/information.service
sdk-setup/systemd/resize-rootfs.service

Old broken links to http://wiki.merproject.org/Platform_SDK were
replaced with links to https://sailfishos.org/wiki/Platform_SDK

[documentation] Fix Platform SDK links. Fixes JB#45357

---

sdk-setup/src/mb2
sdk-setup/src/sdk-manage

In addition to recently **installed/updated** packages, also check the build target for recently **uninstalled** packages when comparing with the known snapshot timestamp.
Caveat:
Parsing `/var/log/zypp/history` is ugly and might break in the future.

sdk-manage: Compare snapshot to recent uninstalled

---

sdk-setup/src/mer-sdk-chroot

Installation path changed with upgrade of dbus to 1.13.12

[mer-sdk-chroot] Fix invocation of dbus-uuidgen. Fixes JB#47723

---

sdk-setup/src/mer-tooling-chroot

Changed cp to use --remove-destination because -f refuses to overwrite
dangling symlinks.

[mer-tooling-chroot] Fix resolv.conf copying. Fixes JB#49950

---

sdk-setup/src/mb2

zypper returns 106 when it has disabled some repository temporarily.
It does not mean that the installation had been unsuccessful.

[mb2] Treat 106 as successful return value for zypper. Fixes JB#46187

---

sdk-setup/src/mb2

By default, when patch notices CRLF line endings in patches, it removes
the CRs. As the files to be patched still have the CRLF line endings,
patch fails. Using binary mode disables the heuristics.

[mb2] Use binary mode when applying patches. Fixes JB#49598

---

sdk-setup/src/sdk-manage

On 64 bit targets, all files which need to be synchronised are stored in /usr/lib64 instead of /usr/lib

Synchronise /usr/lib64 of 64 bit targets

---

rpm/sdk-setup.spec
sdk-setup/src/mb2
sdk-setup/src/ssh-askpass

If any of the default keys requires password, ssh-add would fail. Now
we print a warning instead.

[mb2] Ignore default ssh keys which require password. Fixes JB#50884

---

sdk-setup/src/sdk-manage

The overlay filesystem does not support overwriting a directory in a
single step, like rpm does after rebuilding the db. Luckily, rpm leaves
the newly built db directory in place, so we can just remove the old
one and rename the new one after that.

[sdk-manage] Replace rpmdb in two steps on overlay filesystems. JB#49910

---

sdk-setup/src/sdk-manage

Removing targets regardless of snapshots or mode is needed for SDK
uninstallation.

[sdk-manage] Allow to remove targets with --force. JB#52253

---

sdk-setup/src/sdk-manage

In systemd v238 systemd-machine-id-setup thinks it fails if proc is not
mounted, even if writing machine-id actually succeeded. The second
invocation will correctly detect existing machine-id unless writing
machine-id actually failed.

[sdk-manage] Run systemd-machine-id-setup twice if it fails. JB#52613

---

rpm/sdk-setup.spec

Predicable names are now used by default.

 [sdk-setup] Do not use predicable names for network interaces. Fixes JB#52706

---

sdk-setup/src/sdk-manage

Initial motivation was to just change output from stderr to stdout so
that it is easier to grep the output but as other utils seem to utilize
less for long help change to that instead. This way it's still easy to
grep the help if needed but we use less by default.

Use less to print long help.

---

sdk-setup/src/sdk-manage

[sdk-manage] Don't add trailing slash to tooling path. Fixes JB#55695

---

rpm/sdk-setup.spec
sdk-setup/src/sdk-chroot

The script still has several references to mer. Those will be handled in separate tasks.

[sdk-chroot] Rename mer-sdk-chroot to sdk-chroot. Fixes JB#56734

---

sdk-setup/src/mb2

For some reason comparing timestamps between vboxsf and other
filesystems does not work properly.

[mb2] Fix buildroot timestamp check under VBox. Fixes JB#56804

---

sdk-setup/src/mb2

The state directory may have been left in a wrong place in the past, it makes sense to hint the user that it's safe to remove it.

[mb2] Hint about offending state directory in build-init help. JB#58848
